export const ROUTES = {
  home: '/',
  about: '/about',
  contact: '/contact',
  services: '/services',
  energy: '/energy',
  dataCenters: '/data-centers',
  neocloudz: '/neocloudz',
  careers: '/careers',
  secFilings: '/sec-filings',
  leadership: '/leadership',
  pressRelease: '/press-release',
  investors: '/investors',
  documentsCharters: '/documents-charters',
  privacyPolicy: '/privacy-policy',
  termsOfUse: '/terms-of-use',
  emailAlerts: '/email-alerts',
  missionVision: '/mission-vision',
  globalNetwork: '/global-network',
  partnership: '/partnership',
} as const;
